version: '3.7'
services:
  postgresql:
    image: postgres:14.2
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=elena
      - POSTGRES_PASSWORD=FP7LgFB4ZxsEAk
